version: '3'
services:
  web:
    image: webdevops/php-apache-dev:8.1
    container_name: web_zenx5
    restart: "no"
    user: root
    environment:
      - WEB_ALIAS_DOMAIN=zenx5.pro
      - WEB_DOCUMENT_ROOT=/app
      - PHP_DATE_TIMEZONE=EST
      - PHP_DISPLAY_ERRORS=1
      - PHP_MEMORY_LIMIT=2G
      - PHP_MAX_EXECUTION_TIME=18000
      - PHP_POST_MAX_SIZE=500M
      - PHP_UPLOAD_MAX_FILESIZE=1024M
      - COMPOSER_VERSION=2
    volumes:
      - ./:/app:cached
    ports:
      - "80:80"
      - "443:443"